# frozen_string_literal: true

require './user_permission_tests/test_1005_hr_permissions_update'
require './user_permission_tests/test_1006a_lm_no_permissions'
require './user_permission_tests/test_1006b_linemanager_permissions_update_view'
require './user_permission_tests/test_1006c_lm_view_permissions'
require './user_permission_tests/test_1006d_linemanager_permissions_'
require './user_permission_tests/test_1006e_lm_manage_permissions'
require './user_permission_tests/test_1006f_linemanager_permissions_'
require './user_permission_tests/test_1006g_lm_delete_permissions'
require './user_permission_tests/test_1006h_linemanager_permissions_reset'
require './user_permission_tests/test_1007a_employee_permissions_removal'
require './user_permission_tests/test_1007b_employee_permissions_testing'
require './user_permission_tests/test_1007c_employee_permissions_enabled'
require './user_permission_tests/test_1007d_employee_permissions_positive'
require './user_permission_tests/test_1007e_employee_permissions_return_to_std'
